---
apiVersion: v1
kind: Secret
metadata:
  name: seerr-secret
  namespace: media
type: Opaque
stringData:
  # App
  DB_TYPE: "postgres"
  DB_HOST: "postgres-rw.data.svc.cluster.local"
  DB_PORT: "5432"
  DB_USER: "seerr"
  DB_PASS: "${SEERR_POSTGRES_PASSWORD}"
  DB_NAME: "seerr"
  DB_POOL_SIZE: "10"
  # Postgres Init
  INIT_POSTGRES_DBNAME: seerr
  INIT_POSTGRES_HOST: postgres-rw.data.svc.cluster.local
  INIT_POSTGRES_USER: seerr
  INIT_POSTGRES_PASS: "${SEERR_POSTGRES_PASSWORD}"
  INIT_POSTGRES_SUPER_PASS: "${POSTGRES_SUPER_PASS}"
