---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: hermes
  namespace: ai
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 5Gi
