---
apiVersion: v1
kind: Secret
metadata:
  name: part-db-secret
  namespace: default
type: Opaque
stringData:
  # Postgres Init
  INIT_POSTGRES_DBNAME: partdb
  INIT_POSTGRES_HOST: postgres-rw.data.svc.cluster.local
  INIT_POSTGRES_USER: partdb
  INIT_POSTGRES_PASS: "de743c1ea83eeb9f649d675bb6cbfa63"
  INIT_POSTGRES_SUPER_PASS: "${POSTGRES_SUPER_PASS}"

  # Application
  DATABASE_URL: "postgresql://partdb:de743c1ea83eeb9f649d675bb6cbfa63@postgres-rw.data.svc.cluster.local:5432/partdb?serverVersion=17"
  APP_SECRET: "bed42ec5e3cf64dcd01bae24136fcafcbdff1c931ba3c10a301cac8938c8d2ae"
