---
apiVersion: v1
kind: Secret
metadata:
  name: part-db-secret
  namespace: default
type: Opaque
stringData:
  # Postgres Init
  INIT_POSTGRES_DBNAME: partdb
  INIT_POSTGRES_HOST: postgres-rw.data.svc.cluster.local
  INIT_POSTGRES_USER: "${PART_DB_POSTGRES_USER}"
  INIT_POSTGRES_PASS: "${PART_DB_POSTGRES_PASS}"
  INIT_POSTGRES_SUPER_PASS: "${POSTGRES_SUPER_PASS}"

  # Application
  DATABASE_URL: "postgresql://${PART_DB_POSTGRES_USER}:${PART_DB_POSTGRES_PASS}@postgres-rw.data.svc.cluster.local:5432/partdb?serverVersion=17"
  APP_SECRET: "${PART_DB_APP_SECRET}"
