---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app n8n
  namespace: home
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: app-template
    namespace: flux-system
  values:
    controllers:
      n8n:
        annotations:
          reloader.stakater.com/auto: "true"
        initContainers:
          init-db:
            image:
              repository: ghcr.io/home-operations/postgres-init
              tag: 18@sha256:6fa1f331cddd2eb0b6afa7b8d3685c864127a81ab01c3d9400bc3ff5263a51cf
            envFrom: &envFrom
              - secretRef:
                  name: n8n-secret
          install-actual-api:
            image:
              repository: node
              tag: 20-alpine
            command:
              - sh
              - -c
              - |
                cd /usr/local/lib/node_modules/n8n/node_modules
                npm install @actual-app/api@26.4.0
            securityContext:
              runAsUser: 0
        containers:
          app:
            image:
              repository: ghcr.io/n8n-io/n8n
              tag: 2.18.4@sha256:13e82df0fafc19ad47077e196d6939caaf7364d6d8360605bc328e0c1059b992
            env:
              TZ: ${TIMEZONE}
              GENERIC_TIMEZONE: ${TIMEZONE}
              DB_TYPE: postgresdb
              EXECUTIONS_DATA_PRUNE: true
              EXECUTIONS_DATA_MAX_AGE: 7
              EXECUTIONS_DATA_PRUNE_MAX_COUNT: 50000
              N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS: false
              N8N_PROTOCOL: "https"
              N8N_PORT: &port 8080
              N8N_HOST: n8n.${SECRET_DOMAIN}
              N8N_LOG_LEVEL: info
              N8N_LOG_OUTPUT: console
              NODE_FUNCTION_ALLOW_EXTERNAL: "@actual-app/api"
              NODE_FUNCTION_ALLOW_BUILTIN: "*"
              # N8N_RUNNERS_ENABLED: true
            envFrom: *envFrom
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: false
              capabilities: { drop: ["ALL"] }
            resources:
              requests:
                cpu: 5m
                memory: 128Mi
              limits:
                memory: 2Gi
    defaultPodOptions:
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
        fsGroupChangePolicy: OnRootMismatch
    service:
      app:
        ports:
          http:
            port: *port
    route:
      app:
        hostnames:
          - "{{ .Release.Name }}.${SECRET_DOMAIN}"
        parentRefs:
          - name: internal
            namespace: kube-system
            sectionName: https
    persistence:
      data:
        existingClaim: n8n-config-v1
        globalMounts:
          - path: /home/node/.n8n
