---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/toolhive.stacklok.dev/mcpserver_v1beta1.json
apiVersion: toolhive.stacklok.dev/v1beta1
kind: MCPServer
metadata:
  name: grafana-mcp
spec:
  groupRef:
    name: mcp-tools
  image: grafana/mcp-grafana:0.14.0
  transport: streamable-http
  env:
    - name: GRAFANA_URL
      value: http://grafana-service.monitoring.svc.cluster.local:3000
  secrets:
    - name: grafana-mcp-secret
      key: GRAFANA_SERVICE_ACCOUNT_TOKEN
  podTemplateSpec:
    spec:
      containers:
        - name: mcp
          args:
            - "-t"
            - "streamable-http"
            - "--address"
            - "0.0.0.0:8080"
          ports:
            - containerPort: 8080
              name: mcp
