---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sure-pvc-v1
  namespace: productivity
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  storageClassName: longhorn
