---
apiVersion: v1
kind: Secret
metadata:
  name: sure-secret
  namespace: productivity
type: Opaque
stringData:
  INIT_POSTGRES_DBNAME: sure
  INIT_POSTGRES_HOST: &dbHost postgres-rw.data.svc.cluster.local
  INIT_POSTGRES_USER: "${SURE_POSTGRES_USER}"
  INIT_POSTGRES_PASS: "${SURE_POSTGRES_PASSWORD}"
  INIT_POSTGRES_SUPER_PASS: "${POSTGRES_SUPER_PASS}"

  POSTGRES_USER: "${SURE_POSTGRES_USER}"
  POSTGRES_PASSWORD: "${SURE_POSTGRES_PASSWORD}"
  POSTGRES_DB: sure
  DB_HOST: *dbHost
  DB_PORT: "5432"
  DATABASE_URL: "postgresql://${SURE_POSTGRES_USER}:${SURE_POSTGRES_PASSWORD}@postgres-rw.data.svc.cluster.local:5432/sure"

  SECRET_KEY_BASE: "${SURE_SECRET_KEY_BASE}"

  OIDC_CLIENT_ID: "${SURE_OAUTH_CLIENT_ID}"
  OIDC_CLIENT_SECRET: "${SURE_OAUTH_CLIENT_SECRET}"
