---
# yaml-language-server: $schema=https://raw.githubusercontent.com/recyclarr/recyclarr/refs/tags/v8.0.0/schemas/config-schema.json
sonarr:
  sonarr_main:
    base_url: http://sonarr
    api_key: !env_var SONARR_API_KEY
    delete_old_custom_formats: true
    quality_definition:
      type: series
    quality_profiles:
      - name: WEB-1080p
        trash_id: 72dae194fc92bf828f32cde7744e51a1
        reset_unmatched_scores:
          enabled: true
      - name: Ultra-HD
        trash_id: d1498e7d189fbe6c7110ceaabb7473e6
        reset_unmatched_scores:
          enabled: true
      - name: Remux-1080p - Anime
        trash_id: 20e0fc959f1f1704bed501f23bdae76f
        reset_unmatched_scores:
          enabled: true
    custom_formats:
      - trash_ids:
          - 32b367365729d530ca1c124a0b180c64 # Bad Dual Groups
          - 82d40da2bc6923f41e14394075dd4b03 # No-RlsGroup
          - e1a997ddb54e3ecbfe06341ad323c458 # Obfuscated
          - 06d66ab109d4d2eddb2794d21526d140 # Retags
        assign_scores_to:
          - name: WEB-1080p
          - name: Ultra-HD
          - name: Remux-1080p - Anime

radarr:
  radarr_main:
    base_url: http://radarr
    api_key: !env_var RADARR_API_KEY
    delete_old_custom_formats: true
    quality_definition:
      type: movie
    quality_profiles:
      - name: HD-1080p
        trash_id: d1d67249d3890e49bc12e275d989a7e9
        reset_unmatched_scores:
          enabled: true
      - name: Ultra-HD
        trash_id: 64fb5f9858489bdac2af690e27c8f42f
        reset_unmatched_scores:
          enabled: true
    custom_formats:
      - trash_ids:
          - b6832f586342ef70d9c128d40c07b872 # Bad Dual Groups
          - ae9b7c9ebde1f3bd336a8cbd1ec4c5e5 # No-RlsGroup
          - 7357cf5161efbf8c4d5d0c30b4815ee2 # Obfuscated
          - 5c44f52a8714fdd79bb4d98e2673be1f # Retags
          - f537cf427b64c38c8e36298f657e4828 # Scene
        assign_scores_to:
          - name: HD-1080p
          - name: Ultra-HD
