---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/v1/secret.json
apiVersion: v1
kind: Secret
metadata:
  name: ha-mcp-secret
  namespace: ai
type: Opaque
stringData:
  HOMEASSISTANT_TOKEN: "${HOMEASSISTANT_TOKEN}"
