---
# yaml-language-server: $schema=https://kubernetes-schemas.ok8.sh/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app sparkyfitness
  namespace: flux-system
spec:
  targetNamespace: fitness
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  dependsOn:
    - name: cluster-apps-cloudnative-pg-cluster
  path: ./cluster/apps/fitness/sparkyfitness/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  wait: false
  interval: 30m
  retryInterval: 1m
  timeout: 5m
  decryption:
    provider: sops
    secretRef:
      name: sops-gpg
  postBuild:
    substitute:
      APP: *app
      GATUS_SUBDOMAIN: fitness
    substituteFrom:
      - kind: ConfigMap
        name: cluster-settings
      - kind: Secret
        name: cluster-secrets
