---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dawarich
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 3Gi
