---
apiVersion: v1
kind: Secret
metadata:
  name: dawarich-secret
  namespace: default
type: Opaque
stringData:
  # Postgres Init Container Configuration
  INIT_POSTGRES_DBNAME: dawarich
  INIT_POSTGRES_HOST: postgis-rw.data.svc.cluster.local
  INIT_POSTGRES_USER: "${DAWARICH_POSTGRES_USER}"
  INIT_POSTGRES_PASS: "${DAWARICH_POSTGRES_PASS}"
  INIT_POSTGRES_SUPER_PASS: "${POSTGRES_SUPER_PASS}"

  # Application Database Configuration
  DATABASE_URL: "postgis://${DAWARICH_POSTGRES_USER}:${DAWARICH_POSTGRES_PASS}@postgis-rw.data.svc.cluster.local/dawarich"

  # Application Secrets
  SECRET_KEY_BASE: "${DAWARICH_SECRET_KEY_BASE}"
