---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: grimmory-config-v1
  namespace: books
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi
  storageClassName: longhorn
