---
apiVersion: v1
kind: Secret
metadata:
  name: grimmory-secret
  namespace: books
type: Opaque
stringData:
  DATABASE_PASSWORD: "${GRIMMORY_DB_PASSWORD}"
  MYSQL_ROOT_PASSWORD: "${MARIADB_ROOT_PASSWORD}"
