---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./castai-agent/ks.yaml
  - ./castai-cluster-controller/ks.yaml
  - ./castai-workload-autoscaler-exporter/ks.yaml
  - ./castai-workload-autoscaler/ks.yaml
