---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/v1/secret.json
apiVersion: v1
kind: Secret
metadata:
  name: paperless-secret
  namespace: productivity
type: Opaque
stringData:
  # Database
  PAPERLESS_DBPASS: "${PAPERLESS_DBPASS}"
  # Admin
  PAPERLESS_ADMIN_USER: "${PAPERLESS_ADMIN_USER}"
  PAPERLESS_ADMIN_PASSWORD: "${PAPERLESS_ADMIN_PASSWORD}"
  # Application Secret (signing key for sessions/tokens)
  PAPERLESS_SECRET_KEY: "${PAPERLESS_SECRET_KEY}"
