---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: ai
resources:
  - ./mcpserver.yaml
  # - ./secret.yaml  # enable when GITHUB_TOKEN is added to cluster-secrets.sops.yaml
