---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/v1/secret.json
apiVersion: v1
kind: Secret
metadata:
  name: open-webui-secret
  namespace: ai
type: Opaque
stringData:
  # OIDC / SSO (Authentik)
  OAUTH_CLIENT_ID: "${OPEN_WEBUI_OIDC_CLIENT_ID}"
  OAUTH_CLIENT_SECRET: "${OPEN_WEBUI_OIDC_CLIENT_SECRET}"
