---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: trek-pvc-v1
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi
  storageClassName: longhorn
