---
apiVersion: v1
kind: Secret
metadata:
  name: trek-secret
  namespace: default
type: Opaque
stringData:
  ENCRYPTION_KEY: "${TREK_ENCRYPTION_KEY}"
  OIDC_CLIENT_ID: "${TREK_OAUTH_CLIENT_ID}"
  OIDC_CLIENT_SECRET: "${TREK_OAUTH_CLIENT_SECRET}"
