---
name: Lint Markdown files on Pull Requests

on: # yamllint disable-line rule:truthy
  pull_request:
    paths:
      - "**.md"

jobs:
  markdownlint:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7
      - name: Get changes
        uses: dorny/paths-filter@7b450fff21473bca461d4b92ce414b9d0420d706 # v4
        id: filter
        with:
          list-files: shell
          filters: |
            markdown:
              - added|modified: "**.md"
      - name: Lint files
        if: ${{ steps.filter.outputs.markdown == 'true' }}
        uses: reviewdog/action-shellcheck@4c07458293ac342d477251099501a718ae5ef86e # v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          markdownlint_flags: "-c '.github/lint/.markdownlint.yaml' ${{ steps.filter.outputs.markdown_files }}"
