---
name: Lint Shell scripts on Pull Requests

on: # yamllint disable-line rule:truthy
  pull_request:
    paths:
      - "**.sh"

jobs:
  shellcheck:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7
      - name: Get changes
        uses: dorny/paths-filter@7b450fff21473bca461d4b92ce414b9d0420d706 # v4
        id: filter
        with:
          list-files: shell
          filters: |
            shell:
              - added|modified: "**.sh"
      - name: Lint files
        if: ${{ steps.filter.outputs.shell == 'true' }}
        uses: reviewdog/action-shellcheck@4c07458293ac342d477251099501a718ae5ef86e # v1
        with:
          shellcheck_flags: "${{ steps.filter.outputs.shell_files }}"
